COMPANY_SYMBOLS = {
    "Apple": "AAPL",
    "NVIDIA": "NVDA",
    "Google": "GOOGL",
    "Microsoft": "MSFT",
    "Meta": "META",
    "Amazon": "AMZN",
    "Intel": "INTC",
    "AMD": "AMD",
    "Palantir": "PLTR",
    "C3.ai": "AI",
    "Tesla": "TSLA",
}

# Company name variations for better matching in news articles
COMPANY_VARIATIONS = {
    "Apple": [
        "apple",
        "apple inc",
        "apple inc.",
        "aapl",
        "cupertino",
        "iphone",
        "ipad",
        "mac",
        "tim cook",
    ],
    "NVIDIA": [
        "nvidia",
        "nvda",
        "nvidia corp",
        "nvidia corporation",
        "jensen huang",
        "gpu",
        "geforce",
        "rtx",
    ],
    "Google": [
        "google",
        "googl",
        "alphabet",
        "alphabet inc",
        "sundar pichai",
        "search engine",
        "android",
        "youtube",
    ],
    "Microsoft": [
        "microsoft",
        "msft",
        "microsoft corp",
        "microsoft corporation",
        "satya nadella",
        "windows",
        "azure",
        "office",
    ],
    "Meta": [
        "meta",
        "meta platforms",
        "facebook",
        "instagram",
        "whatsapp",
        "mark zuckerberg",
        "metaverse",
        "oculus",
    ],
    "Amazon": [
        "amazon",
        "amazon.com",
        "amzn",
        "aws",
        "jeff bezos",
        "andy jassy",
        "prime",
        "alexa",
    ],
    "Intel": [
        "intel",
        "intc",
        "intel corp",
        "intel corporation",
        "pat gelsinger",
        "processor",
        "chip",
        "semiconductor",
    ],
    "AMD": [
        "amd",
        "advanced micro devices",
        "lisa su",
        "ryzen",
        "radeon",
        "epyc",
        "processor",
    ],
    "Palantir": [
        "palantir",
        "pltr",
        "palantir technologies",
        "alex karp",
        "data analytics",
        "gotham",
        "foundry",
    ],
    "C3.ai": [
        "c3.ai",
        "c3 ai",
        "ai",
        "artificial intelligence",
        "tom siebel",
        "enterprise ai",
    ],
    "Tesla": [
        "tesla",
        "tsla",
        "tesla inc",
        "elon musk",
        "electric vehicle",
        "ev",
        "model s",
        "model 3",
        "model x",
        "model y",
        "cybertruck",
    ],
}
